name = "website"
compatibility_date = "2025-08-28"

[assets]
directory = "./result"

[[env.production.routes]]
pattern = "theescapement.com"
custom_domain = true

[[env.production.routes]]
pattern = "www.theescapement.com"
custom_domain = true
