name: "Nix common steps"
description: "Install/setup Nix and check flake"
runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31.5.1
      with:
        # DESIGN: matching current in NixOS 25.05
        install_url: https://releases.nixos.org/nix/nix-2.28.4/install

    - name: Setup FlakeHub cache
      uses: DeterminateSystems/flakehub-cache-action@main

    - name: Check flake
      shell: bash
      run: |
        nix --print-build-logs flake check
