const config = {
  subscribe: {
    service: "default_service",
    publicKey: "zmPgTLf8Ez28MtmHD",
    template: {
      staging: "template_52c7x7l",
      production: "template_44wj4bp",
    },
  },
  team: {
    core: [
      "watchanish",
      "rjbroer",
      // "wei_koh_revolution",
      "kingflum",
      "changingtimes001",
      "horoloupe",
      "waitlisted",
    ],
    partners: [
      // "Seddiqi",
      "TheJourneGuy",
      // "nicoleonardvanderhorst",
      "justinhast",
      "SwissWatchGang",
      "andrew_morgan_watches",
      "jacopo_corvo",
      "silas.walton",
      // "langepedia",
      "marc.gebauer",
      "Tony_Traina",
      "watchgirloffduty",
      "Perezscope",
      "s7ndro",
      "nycwatchguy",
      "fumanku",
      // "equationdutemps",
      "changingtimes001",
      "arabwatchguide",
      "unekual",
      "samuelnaldi",
      "Shani.watch",
      "watchstorydxb",
      "watchthetime",
    ],
    toBeAnnounced: ["Perezscope"] as string[],
  },
} as const;

export default config;
