name: Deploy branches to Cloudflare Pages

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "cloudflare-preview-${{ github.head_ref || github.ref_name }}"
  cancel-in-progress: true

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v31.5.1
        with:
          # DESIGN: matching current in NixOS 25.05
          install_url: https://releases.nixos.org/nix/nix-2.28.4/install

      - name: Build site
        run: nix build .#site

      - name: Canonicalize names
        run: |
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          TAG=$(echo ${{ github.sha }} | cut -b -8)
          ALIAS=$(echo "$BRANCH_NAME" | tr './-' '_')
          printf "TAG=%s\nALIAS=%s\n" "$TAG" "$ALIAS" >> $GITHUB_ENV

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          nix develop \
              --command wrangler versions upload \
              --tag "$TAG" \
              --preview-alias "$ALIAS"
